### ISSUE TITLE
Daylight saving

### ISSUE THREAD

**Issue by suderman** [suderman/smsglue#1]
Message timestamp has been incorrectly offset by one hour since daylight saving.

**Comment by spiiiitz** [comment]
Any chance you are working to release an update with a fix for timestamps? Been using your servers to enable SMS for a couple weeks now and it works great, but want to host my own copy so I don't have to rely on providing third parties with creds. Thanks, from a fellow Calgarian! :)

**Comment by suderman** [comment]
I just pushed a workaround which will work until we change our clocks again in the spring. There's a timezone offset available in voip.ms' API, which I may have to expose as a configurable setting if I can't find a way to automatically adjust.

Totally understand wanting to host yourself, that's great. In the meantime, feel good knowing your creds aren't available to me. Your number/username/password are encoded in the custom URLs set in Groundwire, sent to smsglue.com with every request, and not saved to disk.

**Comment by knyzorg** [comment]
@suderman its that time of year again!

**Comment by suderman** [comment]
> @suderman its that time of year again!

Thanks for the heads up—I’ve updated my instance at smsglue.com ⏰

**Comment by suderman** [comment]
Trying something new to avoid having to manually adjust this twice a year. We’ll see if it worked next spring. :-)

**Comment by DFC72** [comment]
I just started using this. Thanks so much for creating it! I think I am having the DST issue here as well. Messages originating from a cell phone into voip.ms and Acrobits are showing an hour ahead. Was there a permanent fix for this through a setting in the API?

Thanks again!

**Comment by suderman** [comment]
No permanent fix, but just now I bounced the service with the timezone adjusted.

**Comment by DFC72** [comment]
Thank you! As a side question (I am new to development) Could I just download this code to a local Linux / Docker container and run it locally with a service exposed to the internet?
