### ISSUE TITLE
SMS not going through

### ISSUE THREAD

**Issue by sheam** [suderman/smsglue#4]
Enabled the API, and went through the SMS glue steps. Copied the URL generated by SMS glue, and entered it into Groundwire. However, when I send an sms to my cel number from groundwire, it does not show up. When I try to send an SMS from my phone to my Voip.ms number, it never shows up in Groundwire either. Groundwire shows a 'check' next to message when I send it, for whatever that is worth.

Is there a way I can trouble shoot this?

Also, in your instructions, I had to use the email address associated with my Voip.ms account, not the SIP username for Voip.ms. I assume this is correct as it generate a URL when I did that?

**Comment by suderman** [comment]
Some troubleshooting can be done by cutting Groundwire out of equation and making sure received messages are arriving on voip.ms' web interface. Anything else requires logging, and you'll need to install the package on your own server and watch what's going on.
