### ISSUE TITLE
not getting passed by Verify my login on Step 3 of https://smsglue.com/

### ISSUE THREAD

**Issue by trentsi** [suderman/smsglue#7]
Hi there,

I am not sure if voip.ms is down or something.

I tried to set up a new account a new iphone and I am not able to bypass the voip.ms user name page anymore on htts://smsglue.com

the error message says: verify my login information and try again.

Any insight?

Thank you for your time.

**Comment by knyzorg** [comment]
I'm getting this as well. Not much debug info available.
![image](https://user-images.githubusercontent.com/10255546/136454557-63d706f2-a60a-4fbf-b7a8-c6cea83bdffc.png)

**Comment by suderman** [comment]
I heard back from voip.ms today and they told me their firewall was blocking us due to the lack of a user-agent in the API requests. Well, I added a user-agent and now I'm getting some messages show up. I believe this is resolved.

Happy (Canadian) Thanksgiving! 🦃

**Comment by knyzorg** [comment]
Confirming that it is now working. Thanks!

**Comment by trentsi** [comment]
reporting some unstable and delays in download sms into groundwire,

It appears the sms stopped showing up in the last 4 days and all of the sudden, they just showed up.( I got them via my email but not landed in groundfire intime)

**Comment by vezaynk** [comment]
@trentsi Same here

**Comment by trentsi** [comment]
pinging @suderman. Please take a further look when you have the chance.

Thank you

**Comment by suderman** [comment]
The TLS certificate for my nginx instance had expired, but I've renewed it now. This wasn't an issue with the NPM package, but just my own instance of it running on smsglue.com.

**Comment by trentsi** [comment]
grateful for your kindness and fast response  @suderman
have a great holiday season.
